name: CI/CD Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./django_chat
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Test with Pytest
      run: |
        python3 -m pip install pytest
        pytest

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.4.1
      with:
        minikube version: 'v1.24.0'
        kubernetes version: 'v1.23.0'
        start args: '--driver=docker'

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag image_name:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml

